services:

  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log/nginx:/var/log/nginx
      - ./:/var/www/html
    depends_on:
      - php-fpm
      - mariadb
    networks:
      - app-network

  php-fpm:
    container_name: ${APP_NAME}_php-fpm
    build:
      context: ./.docker/php-fpm
      args:
        PHP_FPM_VERSION: ${PHP_FPM_VERSION}
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    container_name: ${APP_NAME}_mariadb
    image: mariadb:${MARIADB_VERSION}
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mariadb/data/db/mysql:/var/lib/mysql
      - ./.docker/mariadb/conf.d/my.conf:/etc/mysql/conf.d/my.cnf
      - ./:/var/www/html
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge